export const palavras = [
    ['what is the Design Center?', 'The Design Center is a peer-to-peer design tutoring and collaboration service center at CalArts. It is led by the Design Center Fellow, a Graphic Design program alum, who manages a team of student designers. You can book a time to meet with us for software tutoring, to get advice and feedback on your design, or to have us design something to support your artistic practice'],
    ['What does the Design Center do?', 'We offer three services Tutoring one-on-one software tutoring for Adobe CS and other select software. Collaboration feedback and advice on your project if you need design help. Design design of promotional materials for your exhibition or performance or project.'],
    ['How does de Design Center\'s TUTORING service work?', 'Need help with Photoshop, Illustrator, or other Adobe creative software? We’re here to help! Peer tutors are current graphic design students who have already stayed up until 2:00am skimming YouTube tutorials so you don’t have to. Make an appointment for a peer-to-peer meeting to learn the ins and outs of design programs and get your questions answered.'],
    ['How does the Design Center\'s COLLABORATION service work?', 'This service is perfect if you love creating your own designs but want to level up. Book a collaboration appointment to get feedback on your design. Get help with fixing typography, funky color contrasts, or awkward compositions. We try to focus on what’s working and build from there to get your work to a higher level.'],
    ['How does the Design Center\'s DESIGN service work?', 'This service is perfect for when you need a designer to create materials related to your artistic practice. Tell us your ideas, bring your content (text and images), and we will create two design options for you. You pick one and your designer will refine it for you. We will explain the process and guidelines further at our first meeting. We aim to keep both you and the designer happy with the process and resulting design'],
    ['What can you design for me?', 'Posters, visual identity, social media posts, publications, music packaging, t-shirts, exhibition graphics, film titles, websites, and more…\n' +
    '\n' +
    'Pretty much anything that uses type and images to publicize or promote your work.'],
    ['How do i get stared?', 'Sign up for an appointment, either with a specific tutor or any available slot. Then meet us at the Design Center (D214c, around the corner from Tatum Lounge) and tell us about your project and learn how we work.'],
    ['Can i just drop by without an appointment?', 'If you have a quick question you can just stop by D214c.\n' +
    'Monday 4–7pm\n' +
    'Wednesday 1–7 pm\n' +
    'Thursday 1–7 pm'],
    ['Is there a cost involved?', 'Our tutoring services are free to students, faculty, and staff.\n' +
    '\n' +
    'Design services are free when the design is used for non-profit student projects (e.g. you need a poster designed for your show or exhibition).\n' +
    '\n' +
    'Larger or commercial projects are at the discretion of the Design Center Fellow and the availability of student workers.'],
    ['Can i get free prints?', 'We will print 20 color laser prints (11x17) of the posters we design for you—free of charge. If you want to produce designs in other media (screen printing, vinyl, etc.), you will be responsible for the cost of materials and labor.'],
    ['How is the Design Center funded?', 'The Design Center is funded by external revenue from Coursera generated by CalArts Graphic Design program faculty.']
];